package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AccessKeyType generated by hbm2java
 */
public class AccessKeyType implements java.io.Serializable {

	private String accessKeyTypeCd;
	private String accessKeyTypeDescription;
	private Set<AccessKey> accessKeys = new HashSet<AccessKey>(0);

	public AccessKeyType() {
	}

	public AccessKeyType(String accessKeyTypeCd) {
		this.accessKeyTypeCd = accessKeyTypeCd;
	}

	public AccessKeyType(String accessKeyTypeCd,
			String accessKeyTypeDescription, Set<AccessKey> accessKeys) {
		this.accessKeyTypeCd = accessKeyTypeCd;
		this.accessKeyTypeDescription = accessKeyTypeDescription;
		this.accessKeys = accessKeys;
	}

	public String getAccessKeyTypeCd() {
		return this.accessKeyTypeCd;
	}

	public void setAccessKeyTypeCd(String accessKeyTypeCd) {
		this.accessKeyTypeCd = accessKeyTypeCd;
	}

	public String getAccessKeyTypeDescription() {
		return this.accessKeyTypeDescription;
	}

	public void setAccessKeyTypeDescription(String accessKeyTypeDescription) {
		this.accessKeyTypeDescription = accessKeyTypeDescription;
	}

	public Set<AccessKey> getAccessKeys() {
		return this.accessKeys;
	}

	public void setAccessKeys(Set<AccessKey> accessKeys) {
		this.accessKeys = accessKeys;
	}

}
