package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * AccessKey generated by hbm2java
 */
public class AccessKey implements java.io.Serializable {

	private int accessKeyId;
	private AccessKeyType accessKeyType;
	private String accessKeyData;
	private String accessKeyPrincipal;
	private NodeAccessKeys nodeAccessKeys;

	public AccessKey() {
	}

	public AccessKey(int accessKeyId) {
		this.accessKeyId = accessKeyId;
	}

	public AccessKey(int accessKeyId, AccessKeyType accessKeyType,
			String accessKeyData, String accessKeyPrincipal,
			NodeAccessKeys nodeAccessKeys) {
		this.accessKeyId = accessKeyId;
		this.accessKeyType = accessKeyType;
		this.accessKeyData = accessKeyData;
		this.accessKeyPrincipal = accessKeyPrincipal;
		this.nodeAccessKeys = nodeAccessKeys;
	}

	public int getAccessKeyId() {
		return this.accessKeyId;
	}

	public void setAccessKeyId(int accessKeyId) {
		this.accessKeyId = accessKeyId;
	}

	public AccessKeyType getAccessKeyType() {
		return this.accessKeyType;
	}

	public void setAccessKeyType(AccessKeyType accessKeyType) {
		this.accessKeyType = accessKeyType;
	}

	public String getAccessKeyData() {
		return this.accessKeyData;
	}

	public void setAccessKeyData(String accessKeyData) {
		this.accessKeyData = accessKeyData;
	}

	public String getAccessKeyPrincipal() {
		return this.accessKeyPrincipal;
	}

	public void setAccessKeyPrincipal(String accessKeyPrincipal) {
		this.accessKeyPrincipal = accessKeyPrincipal;
	}

	public NodeAccessKeys getNodeAccessKeys() {
		return this.nodeAccessKeys;
	}

	public void setNodeAccessKeys(NodeAccessKeys nodeAccessKeys) {
		this.nodeAccessKeys = nodeAccessKeys;
	}

}
