package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	private int appId;
	private String appDesc;
	private String appName;
	private Set<ProfileApplications> profileApplicationses = new HashSet<ProfileApplications>(
			0);
	private Set<Environment> environments = new HashSet<Environment>(0);

	public Application() {
	}

	public Application(int appId) {
		this.appId = appId;
	}

	public Application(int appId, String appDesc, String appName,
			Set<ProfileApplications> profileApplicationses,
			Set<Environment> environments) {
		this.appId = appId;
		this.appDesc = appDesc;
		this.appName = appName;
		this.profileApplicationses = profileApplicationses;
		this.environments = environments;
	}

	public int getAppId() {
		return this.appId;
	}

	public void setAppId(int appId) {
		this.appId = appId;
	}

	public String getAppDesc() {
		return this.appDesc;
	}

	public void setAppDesc(String appDesc) {
		this.appDesc = appDesc;
	}

	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public Set<ProfileApplications> getProfileApplicationses() {
		return this.profileApplicationses;
	}

	public void setProfileApplicationses(
			Set<ProfileApplications> profileApplicationses) {
		this.profileApplicationses = profileApplicationses;
	}

	public Set<Environment> getEnvironments() {
		return this.environments;
	}

	public void setEnvironments(Set<Environment> environments) {
		this.environments = environments;
	}

}
