package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ArtifactType generated by hbm2java
 */
public class ArtifactType implements java.io.Serializable {

	private String artifactTypeCd;
	private String articfactTypeDesc;
	private Set<NodeArtifact> nodeArtifacts = new HashSet<NodeArtifact>(0);

	public ArtifactType() {
	}

	public ArtifactType(String artifactTypeCd) {
		this.artifactTypeCd = artifactTypeCd;
	}

	public ArtifactType(String artifactTypeCd, String articfactTypeDesc,
			Set<NodeArtifact> nodeArtifacts) {
		this.artifactTypeCd = artifactTypeCd;
		this.articfactTypeDesc = articfactTypeDesc;
		this.nodeArtifacts = nodeArtifacts;
	}

	public String getArtifactTypeCd() {
		return this.artifactTypeCd;
	}

	public void setArtifactTypeCd(String artifactTypeCd) {
		this.artifactTypeCd = artifactTypeCd;
	}

	public String getArticfactTypeDesc() {
		return this.articfactTypeDesc;
	}

	public void setArticfactTypeDesc(String articfactTypeDesc) {
		this.articfactTypeDesc = articfactTypeDesc;
	}

	public Set<NodeArtifact> getNodeArtifacts() {
		return this.nodeArtifacts;
	}

	public void setNodeArtifacts(Set<NodeArtifact> nodeArtifacts) {
		this.nodeArtifacts = nodeArtifacts;
	}

}
