package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * EnivronmentNodes generated by hbm2java
 */
public class EnivronmentNodes implements java.io.Serializable {

	private int envId;
	private Environment environment;
	private Node node;

	public EnivronmentNodes() {
	}

	public EnivronmentNodes(Environment environment, Node node) {
		this.environment = environment;
		this.node = node;
	}

	public int getEnvId() {
		return this.envId;
	}

	public void setEnvId(int envId) {
		this.envId = envId;
	}

	public Environment getEnvironment() {
		return this.environment;
	}

	public void setEnvironment(Environment environment) {
		this.environment = environment;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

}
