package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * EnvironmentId generated by hbm2java
 */
public class EnvironmentId implements java.io.Serializable {

	private int envId;
	private String envTypeCd;

	public EnvironmentId() {
	}

	public EnvironmentId(int envId, String envTypeCd) {
		this.envId = envId;
		this.envTypeCd = envTypeCd;
	}

	public int getEnvId() {
		return this.envId;
	}

	public void setEnvId(int envId) {
		this.envId = envId;
	}

	public String getEnvTypeCd() {
		return this.envTypeCd;
	}

	public void setEnvTypeCd(String envTypeCd) {
		this.envTypeCd = envTypeCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnvironmentId))
			return false;
		EnvironmentId castOther = (EnvironmentId) other;

		return (this.getEnvId() == castOther.getEnvId())
				&& ((this.getEnvTypeCd() == castOther.getEnvTypeCd()) || (this
						.getEnvTypeCd() != null
						&& castOther.getEnvTypeCd() != null && this
						.getEnvTypeCd().equals(castOther.getEnvTypeCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEnvId();
		result = 37 * result
				+ (getEnvTypeCd() == null ? 0 : this.getEnvTypeCd().hashCode());
		return result;
	}

}
