package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Environment generated by hbm2java
 */
public class Environment implements java.io.Serializable {

	private EnvironmentId id;
	private EnvironmentType environmentType;
	private String envName;
	private String envDescription;
	private Set<Application> applications = new HashSet<Application>(0);
	private EnivronmentNodes enivronmentNodes;

	public Environment() {
	}

	public Environment(EnvironmentId id, EnvironmentType environmentType) {
		this.id = id;
		this.environmentType = environmentType;
	}

	public Environment(EnvironmentId id, EnvironmentType environmentType,
			String envName, String envDescription,
			Set<Application> applications, EnivronmentNodes enivronmentNodes) {
		this.id = id;
		this.environmentType = environmentType;
		this.envName = envName;
		this.envDescription = envDescription;
		this.applications = applications;
		this.enivronmentNodes = enivronmentNodes;
	}

	public EnvironmentId getId() {
		return this.id;
	}

	public void setId(EnvironmentId id) {
		this.id = id;
	}

	public EnvironmentType getEnvironmentType() {
		return this.environmentType;
	}

	public void setEnvironmentType(EnvironmentType environmentType) {
		this.environmentType = environmentType;
	}

	public String getEnvName() {
		return this.envName;
	}

	public void setEnvName(String envName) {
		this.envName = envName;
	}

	public String getEnvDescription() {
		return this.envDescription;
	}

	public void setEnvDescription(String envDescription) {
		this.envDescription = envDescription;
	}

	public Set<Application> getApplications() {
		return this.applications;
	}

	public void setApplications(Set<Application> applications) {
		this.applications = applications;
	}

	public EnivronmentNodes getEnivronmentNodes() {
		return this.enivronmentNodes;
	}

	public void setEnivronmentNodes(EnivronmentNodes enivronmentNodes) {
		this.enivronmentNodes = enivronmentNodes;
	}

}
