package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EnvironmentType generated by hbm2java
 */
public class EnvironmentType implements java.io.Serializable {

	private String envTypeCd;
	private String envTypeDescription;
	private Set<Environment> environments = new HashSet<Environment>(0);

	public EnvironmentType() {
	}

	public EnvironmentType(String envTypeCd) {
		this.envTypeCd = envTypeCd;
	}

	public EnvironmentType(String envTypeCd, String envTypeDescription,
			Set<Environment> environments) {
		this.envTypeCd = envTypeCd;
		this.envTypeDescription = envTypeDescription;
		this.environments = environments;
	}

	public String getEnvTypeCd() {
		return this.envTypeCd;
	}

	public void setEnvTypeCd(String envTypeCd) {
		this.envTypeCd = envTypeCd;
	}

	public String getEnvTypeDescription() {
		return this.envTypeDescription;
	}

	public void setEnvTypeDescription(String envTypeDescription) {
		this.envTypeDescription = envTypeDescription;
	}

	public Set<Environment> getEnvironments() {
		return this.environments;
	}

	public void setEnvironments(Set<Environment> environments) {
		this.environments = environments;
	}

}
