package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Node generated by hbm2java
 */
public class Node implements java.io.Serializable {

	private int nodeId;
	private String nodeName;
	private String nodeDesc;
	private String nodeHostname;
	private Set<NodeAccessKeys> nodeAccessKeyses = new HashSet<NodeAccessKeys>(
			0);
	private Set<EnivronmentNodes> enivronmentNodeses = new HashSet<EnivronmentNodes>(
			0);
	private Set<NodeArtifact> nodeArtifacts = new HashSet<NodeArtifact>(0);

	public Node() {
	}

	public Node(int nodeId) {
		this.nodeId = nodeId;
	}

	public Node(int nodeId, String nodeName, String nodeDesc,
			String nodeHostname, Set<NodeAccessKeys> nodeAccessKeyses,
			Set<EnivronmentNodes> enivronmentNodeses,
			Set<NodeArtifact> nodeArtifacts) {
		this.nodeId = nodeId;
		this.nodeName = nodeName;
		this.nodeDesc = nodeDesc;
		this.nodeHostname = nodeHostname;
		this.nodeAccessKeyses = nodeAccessKeyses;
		this.enivronmentNodeses = enivronmentNodeses;
		this.nodeArtifacts = nodeArtifacts;
	}

	public int getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(int nodeId) {
		this.nodeId = nodeId;
	}

	public String getNodeName() {
		return this.nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

	public String getNodeDesc() {
		return this.nodeDesc;
	}

	public void setNodeDesc(String nodeDesc) {
		this.nodeDesc = nodeDesc;
	}

	public String getNodeHostname() {
		return this.nodeHostname;
	}

	public void setNodeHostname(String nodeHostname) {
		this.nodeHostname = nodeHostname;
	}

	public Set<NodeAccessKeys> getNodeAccessKeyses() {
		return this.nodeAccessKeyses;
	}

	public void setNodeAccessKeyses(Set<NodeAccessKeys> nodeAccessKeyses) {
		this.nodeAccessKeyses = nodeAccessKeyses;
	}

	public Set<EnivronmentNodes> getEnivronmentNodeses() {
		return this.enivronmentNodeses;
	}

	public void setEnivronmentNodeses(Set<EnivronmentNodes> enivronmentNodeses) {
		this.enivronmentNodeses = enivronmentNodeses;
	}

	public Set<NodeArtifact> getNodeArtifacts() {
		return this.nodeArtifacts;
	}

	public void setNodeArtifacts(Set<NodeArtifact> nodeArtifacts) {
		this.nodeArtifacts = nodeArtifacts;
	}

}
