package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * NodeAccessKeys generated by hbm2java
 */
public class NodeAccessKeys implements java.io.Serializable {

	private int accessKeyId;
	private AccessKey accessKey;
	private Node node;

	public NodeAccessKeys() {
	}

	public NodeAccessKeys(AccessKey accessKey, Node node) {
		this.accessKey = accessKey;
		this.node = node;
	}

	public int getAccessKeyId() {
		return this.accessKeyId;
	}

	public void setAccessKeyId(int accessKeyId) {
		this.accessKeyId = accessKeyId;
	}

	public AccessKey getAccessKey() {
		return this.accessKey;
	}

	public void setAccessKey(AccessKey accessKey) {
		this.accessKey = accessKey;
	}

	public Node getNode() {
		return this.node;
	}

	public void setNode(Node node) {
		this.node = node;
	}

}
