package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * NodeArtifact generated by hbm2java
 */
public class NodeArtifact implements java.io.Serializable {

	private int nodeArtifactId;
	private ArtifactType artifactType;
	private String artifactLocation;
	private Set<Node> nodes = new HashSet<Node>(0);

	public NodeArtifact() {
	}

	public NodeArtifact(int nodeArtifactId, ArtifactType artifactType) {
		this.nodeArtifactId = nodeArtifactId;
		this.artifactType = artifactType;
	}

	public NodeArtifact(int nodeArtifactId, ArtifactType artifactType,
			String artifactLocation, Set<Node> nodes) {
		this.nodeArtifactId = nodeArtifactId;
		this.artifactType = artifactType;
		this.artifactLocation = artifactLocation;
		this.nodes = nodes;
	}

	public int getNodeArtifactId() {
		return this.nodeArtifactId;
	}

	public void setNodeArtifactId(int nodeArtifactId) {
		this.nodeArtifactId = nodeArtifactId;
	}

	public ArtifactType getArtifactType() {
		return this.artifactType;
	}

	public void setArtifactType(ArtifactType artifactType) {
		this.artifactType = artifactType;
	}

	public String getArtifactLocation() {
		return this.artifactLocation;
	}

	public void setArtifactLocation(String artifactLocation) {
		this.artifactLocation = artifactLocation;
	}

	public Set<Node> getNodes() {
		return this.nodes;
	}

	public void setNodes(Set<Node> nodes) {
		this.nodes = nodes;
	}

}
