package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private int profileId;
	private UserProfiles userProfiles;
	private String profileDesc;
	private String profileName;
	private ProfileApplications profileApplications;

	public Profile() {
	}

	public Profile(UserProfiles userProfiles) {
		this.userProfiles = userProfiles;
	}

	public Profile(UserProfiles userProfiles, String profileDesc,
			String profileName, ProfileApplications profileApplications) {
		this.userProfiles = userProfiles;
		this.profileDesc = profileDesc;
		this.profileName = profileName;
		this.profileApplications = profileApplications;
	}

	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	public UserProfiles getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(UserProfiles userProfiles) {
		this.userProfiles = userProfiles;
	}

	public String getProfileDesc() {
		return this.profileDesc;
	}

	public void setProfileDesc(String profileDesc) {
		this.profileDesc = profileDesc;
	}

	public String getProfileName() {
		return this.profileName;
	}

	public void setProfileName(String profileName) {
		this.profileName = profileName;
	}

	public ProfileApplications getProfileApplications() {
		return this.profileApplications;
	}

	public void setProfileApplications(ProfileApplications profileApplications) {
		this.profileApplications = profileApplications;
	}

}
