package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfiles generated by hbm2java
 */
public class UserProfiles implements java.io.Serializable {

	private UserProfilesId id;
	private User user;
	private Profile profile;

	public UserProfiles() {
	}

	public UserProfiles(UserProfilesId id, User user) {
		this.id = id;
		this.user = user;
	}

	public UserProfiles(UserProfilesId id, User user, Profile profile) {
		this.id = id;
		this.user = user;
		this.profile = profile;
	}

	public UserProfilesId getId() {
		return this.id;
	}

	public void setId(UserProfilesId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

}
