package com.dreeling.applications.ocelli.server.domain;

// Generated May 27, 2014 9:55:07 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfilesId generated by hbm2java
 */
public class UserProfilesId implements java.io.Serializable {

	private int profileId;
	private String userId;

	public UserProfilesId() {
	}

	public UserProfilesId(int profileId, String userId) {
		this.profileId = profileId;
		this.userId = userId;
	}

	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserProfilesId))
			return false;
		UserProfilesId castOther = (UserProfilesId) other;

		return (this.getProfileId() == castOther.getProfileId())
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProfileId();
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
